site_name: PKT Documentation
site_url: https://coconut3-dev.github.io/dev_docs_pkt_cash.github.io/
site_author: Coconut3
site_description: "Dev environment"
repo_url: "https://github.com/coconut3-dev/dev_docs_pkt_cash.github.io"

# theme:
#   name: null
#   custom_dir: pkt
#   colorscheme: github
#   highlightjs: true

theme:
  name: moonstone
  custom_dir: custom_theme

nav:
  - Home: index.md
  - PKT Documentation: documentation.md
  - PKT Electrum: electrum/index.md
  - Mining: mining/index.md
  - Pool Operation: mining/pool_setup_guide.md
  - Pktd: pktd/index.md
  - PKTWallet: pktd/pktwallet.md
  - Wrapped PKT: wrapped_pkt.md
  - Electrum Import: pktd/migrating_from_electrum.md
  - FAQ: PKT_FAQ.md
  - Code of Conduct: code_of_conduct.md
  - Commercial: commercial.md
  - Useful Tools: useful_tools.md
  - Communication: communication.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list

extra_css:
    - css/extra.css